# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelocation',
            name='floorplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geo.FloorPlan'),
        ),
        migrations.AlterField(
            model_name='devicelocation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geo.Location'),
        ),
    ]
