# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openwisp_users', '0001_initial'),
        ('geo', '0002_auto_20171002_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplan',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, db_index=True, max_length=256, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=75, verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('name', 'organization')]),
        ),
    ]
