# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20170925_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelocation',
            name='indoor_coords',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='indoor position'),
        ),
    ]
