# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_auto_20170928_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicelocation',
            old_name='floor',
            new_name='floorplan',
        ),
        migrations.RenameField(
            model_name='devicelocation',
            old_name='indoor_coords',
            new_name='indoor',
        ),
    ]
