# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openwisp_users', '0001_initial'),
        ('geo', '0005_auto_20170928_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='notes',
        ),
        migrations.AddField(
            model_name='floorplan',
            name='organization',
            field=models.ForeignKey(default='5de4d037-678d-467b-bb8d-dbc7d612cf20', on_delete=django.db.models.deletion.CASCADE, to='openwisp_users.Organization', verbose_name='organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(default='5de4d037-678d-467b-bb8d-dbc7d612cf20', max_length=128, verbose_name='address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='organization',
            field=models.ForeignKey(default='5de4d037-678d-467b-bb8d-dbc7d612cf20', on_delete=django.db.models.deletion.CASCADE, to='openwisp_users.Organization', verbose_name='organization'),
            preserve_default=False,
        ),
    ]
