# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_auto_20170928_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelocation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Location'),
        ),
        migrations.AlterField(
            model_name='devicelocation',
            name='type',
            field=models.CharField(choices=[('outdoor', 'Outdoor'), ('indoor', 'Indoor'), ('mobile', 'Mobile')], max_length=8),
        ),
    ]
